version: '3.7'

services:
  cloud-guard-client:
    container_name: cloud-guard-client
    image: cloud-guard-client-img
    restart: always
    build:
      context: ./cloud-guard-client
      target: frontend-builder
    ports:
      - 4200:4200
    volumes:
      - ./cloud-guard-client/src:/app/src
      - ./cloud-guard-client/node_modules:/app/node_modules